version: "3.9"

services:
  app:
    container_name: medoptix_app_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 app.main:app